apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: "{{ .Release.Name }}-resource-alerts"
  labels:
    release: prometheus
spec:
  groups:
  - name: nti-alerts
    rules:
    - alert: HighCPUUsage
      expr: node_load1 > 0.80
      for: 2m
      annotations:
        summary: "CPU Usage > 80% on {{ "{{" }} $labels.instance {{ "}}" }}"
    - alert: HighRAMUsage
      expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.80
      for: 2m
      annotations:
        summary: "RAM Usage > 80% on {{ "{{" }} $labels.instance {{ "}}" }}"