aws_region           = "us-east-1"
environment          = "dev"
cluster_name         = "nti-eks-cluster"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.101.0/24", "10.0.102.0/24"]
private_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24"]
ami_id        = "ami-0b6d9d3d33ba97d99" 
instance_type = "c7i-flex.large"
public_key_path = "./jenkins_key.pub"
db_name           = "final_project_db"
db_username       = "admin"
db_instance_class = "db.t3.micro"
ecr_repository_names = ["frontend-app", "backend-app"]
node_instance_type = "c7i-flex.large"
desired_nodes      = 2
min_nodes          = 2
max_nodes          = 4