---
- name: Install and Configure CloudWatch Agent
  hosts: jenkins
  become: true
  tasks:
    - name: Download Amazon CloudWatch Agent Package
      ansible.builtin.get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dest: /tmp/amazon-cloudwatch-agent.deb
        mode: '0644'

    - name: Install CloudWatch Agent Package
      ansible.builtin.apt:
        deb: /tmp/amazon-cloudwatch-agent.deb
        state: present

    - name: Create CloudWatch Agent Configuration Directory
      ansible.builtin.file:
        path: /opt/aws/amazon-cloudwatch-agent/etc
        state: directory
        mode: '0755'

    - name: Copy CloudWatch Agent Configuration File
      ansible.builtin.copy:
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        mode: '0644'
        content: |
          {
            "agent": {
              "metrics_collection_interval": 60,
              "run_as_user": "cwagent"
            },
            "metrics": {
              "metrics_collected": {
                "disk": {
                  "measurement": ["used_percent"],
                  "metrics_collection_interval": 60,
                  "resources": ["*"]
                },
                "mem": {
                  "measurement": ["mem_used_percent"],
                  "metrics_collection_interval": 60
                }
              }
            }
          }

    - name: Start and Enable CloudWatch Agent
      ansible.builtin.systemd:
        name: amazon-cloudwatch-agent
        state: restarted
        enabled: true
